### ISSUE TITLE
[bug] Fixes to research page(s)

### ISSUE THREAD

**Issue by alecive** [HIRO-group/HIRO-group.github.io#130]
**Describe the bug**
The research pages are really boring. We need pics!

**To Reproduce**
Go to the research page or any of the subteams and be sad.

**Expected behavior**
Being happy!!

**Screenshots**
A screenshot would increase my pain

**Things to address**

- [ ] One picture (or two) per subteam in research page
- [x] One picture per subproject in subteam pages (at least, those that have pictures)
- [x] Algorithmic and Social HRI page does not have students in subprojects

@joewie I summon you to take care of this. Thanks!

**Comment by joewie** [comment]
Note to self and/or Matt: Add subteam descriptions as well.

**Comment by joewie** [comment]
Mostly addressed in [this commit](https://github.com/HIRO-group/HIRO-group.github.io/commit/1bc948fad9b0a948b753e311b9ada58073b411df). Each subteam has an image on the front page, but not on `research.html`. Honestly, I like `research.html` the way it is.

**Comment by alecive** [comment]
I would actually like to have the pics in the research section as well. It's really flat right now!
