### ISSUE TITLE
[bug] Clean-up of unused/merged branches

### ISSUE THREAD

**Issue by alecive** [HIRO-group/HIRO-group.github.io#138]
As per title. I summon @peasant98 for this!

**Comment by peasant98** [comment]
Done -- now we're left with master and the two current PRs' branches.

**Comment by alecive** [comment]
While I'm not sure you have spent any time checking if those branches were actually useful, fell free to close the issue.

**Comment by peasant98** [comment]
I deleted the already merged branches, so it's all good
