### ISSUE TITLE
[bug] Add Jake's and Kaleb's paper

### ISSUE THREAD

**Issue by alecive** [HIRO-group/HIRO-group.github.io#197]
As per title.

- [x] Add PDF and BIB
- [x] Add it to the publications page with all the proper tags
- [x] Add it to Arxiv
- [x] Add a small little news article about it --- not needed, just a workshop
- [x] Add a paper page --- not needed, just a workshop

**Comment by alecive** [comment]
@kalebishop @JakeBrawer updates?

**Comment by JakeBrawer** [comment]
Sorry we’ll have it done by Monday

**Comment by alecive** [comment]
@JakeBrawer update?

**Comment by JakeBrawer** [comment]
Its done, sorry for the delay
