### ISSUE TITLE
[bug] Refreshing "Learning, Modeling, and Robotics" page 

### ISSUE THREAD

**Issue by alecive** [HIRO-group/HIRO-group.github.io#200]
As the new PhD admission cycle is starting, we need to do a better job at showing what it is we are interested in. We need to updated [this page](https://hiro-group.ronc.one/subteam/learning-modeling-robotics.html) accordingly. 

How to go about that? 

Options: 

1. We meet 1 hour and take care of it synchronously
2. We start writing here all the new paragraphs / sections we want to add / update, and then open a PR with the goal of closing it in ~2 weeks

(Note: I wanted to add Chi-Hui here too but he is not on our github?)

**Comment by a-nooj** [comment]
@joewie can you add Nathan to our GitHub? I don't have his ID.

**Comment by alecive** [comment]
What's missing now is to refresh the main page : https://hiro-group.ronc.one/research

Also, plase have two figs like the phri team has

**Comment by alecive** [comment]
@a-nooj updates?
