### ISSUE TITLE
[bug] Refreshing the Physical HRI page 

### ISSUE THREAD

**Issue by alecive** [HIRO-group/HIRO-group.github.io#201]
As the new PhD admission cycle is starting, we need to do a better job at showing what it is we are interested in. We need to updated [this page](https://hiro-group.ronc.one/subteam/control-artificial-skin) accordingly. 

How to go about that? 

Options: 

1. We meet 1 hour and take care of it synchronously
2. We start writing here all the new paragraphs / sections we want to add / update, and then open a PR with the goal of closing it in ~2 weeks

**Comment by alecive** [comment]
I can do next Wednesday at the earliest (if you want me)

**Comment by JakeBrawer** [comment]
I think it'd definitely be helpful to have you involved though I will be DC for the AAAI symposium next Wed.

**Comment by alecive** [comment]
@nataliya-dev @calebescobedo what's missing here?
