### ISSUE TITLE
[feature] Add Mathjax

### ISSUE THREAD

**Issue by alecive** [HIRO-group/HIRO-group.github.io#92]
As per title. 

This one seems a good resource https://haixing-hu.github.io/programming/2013/09/20/how-to-use-mathjax-in-jekyll-generated-github-pages/

**Comment by joewie** [comment]
Turns out we do have [MathJax](https://github.com/HIRO-group/HIRO-group.github.io/blob/fedc3fc282509c9a35933d1db94e9f4fe1592f87/_includes/head.html#L70-L83).

**Comment by alecive** [comment]
Ha ha lol I must have forgotten about it. Let's keep this open until we actually try to use it.

**Comment by calebescobedo** [comment]
Did anyone use MathJax to generate equations yet? @aran159 and I are adding some to the roboskin page now and would like to know if someone already knows the workflow for MathJax. 

In the link you shared @alecive they recommend changing the markdown processor to maruku, we currently use kramdown. Do we need to keep kramdown to render some specific part of the website? If not do you know if I can just change the processor?

**Comment by calebescobedo** [comment]
I used [this](https://lyk6756.github.io/2016/11/25/write_latex_equations.html) method to allow equations using kramdown as our processor. I changed the MathJax import statement in the head.html, do you know if MathJax was used anywhere else and this would cause an error?

**Comment by alecive** [comment]
Good to me @calebescobedo . If it works with kramdown it'd be better because it's just more powerful than maruku and its features are used throughout the website (for example, to have ToC's in articles). I'll close this issue then. If you get any problem with the current setup, let's chat!
