### ISSUE TITLE
Remove people that are not working in the lab any more 

### ISSUE THREAD

**Issue by alecive** [HIRO-group/HIRO-group.github.io#95]
* CJ , now at Zoox
 * Max page
 * Sousheel, now at Amazon
 * Jacob Fiola
 * Rebecca 
 * Kyle Pformer (@a-nooj  is he still working with us?)
 * Liyang

**Comment by alecive** [comment]
@dhruvpatelaj

**Comment by peasant98** [comment]
Dhruv is with us; he's on roboskin team with Kandai.

**Comment by alecive** [comment]
Sorry, I tagged him because he shold take care of the issue! Not because I want to kick him out :-)

**Comment by alecive** [comment]
For some reason I can't assign the issue to them--it doesn't make any sense

**Comment by joewie** [comment]
> For some reason I can't assign the issue to them--it doesn't make any sense

Fixed some permissions, should work in the future.

**Comment by dhruvpatelaj** [comment]
closed in #100
